### ISSUE TITLE
Possible solution to Android stuck on black screen

### ISSUE THREAD

**Issue by reflexit** [kavezo/ZipZap#11]
It seems that a number of Android users are stuck on black screen and unable to reach the title screen, despite following all the required steps. ProxyDroid might be a solution, but in my particular case it didn't work either. After some research, I finally made it work, so I share my steps here. Note that the following steps require a **rooted** device or emulator (I use Android-x86 in VirtualBox).

0. Start server according to README.
1. On the client, install ProxyDroid, configure the proxy ip address and port, and start proxy.
2. Visit mitm.it, download and install the user CA according to README.
3. With root access, move the installed user CA to system CA by [this guide](https://gist.github.com/pwlin/8a0d01e6428b7a96e2eb).
4. Reboot your device or emulator.
5. After reboot, start ProxyDroid before starting server. Now launch the game and you should be able to connect to your private server.

In my case, **both step 3 and 4** are necessary. Hope this will help other users with similar issues.

And last, a huge thanks to all developers involved!

**Comment by kavezo** [comment]
great! I'll forward this to the tutorial writers!

**Comment by reflexit** [comment]
Since the server doesn't use mitmproxy any more, the steps above are no longer applicable. Therefore, I think this issue can be safely closed.
