### ISSUE TITLE
Error Trying to level up Memorias

### ISSUE THREAD

**Issue by gvaldebenit** [kavezo/ZipZap#2]
Hi. I don't know if you want things like issues on things as hard as this project, but I will leave it as just a way to make it better for community. Feel free to ignore it if you want.

So, I tried to level up a memoria (to make memoria space), and then an error arise on console. (On app, say something like "Connection Error, Reload").

Error point to _api\userPiece.py_. Line 204. Then go to Line 110 (Limit Break, idk why) and says _userPiece['piece']['pieceKind']=='LIMIT_BREAK'_  '**pieceKind': Wrong Key**

Is important to note I'm using memoria enhance, not memoria ascend, and using some 1* memoria (The familiar memos).

Thanks for your big efforts on this proyect.

**Comment by gvaldebenit** [comment]
Also, not related to this, but I made an Script during class to make the enviroment on a easy way to most people. It uses this two bat files put with the others. Is not much, but I hope serves as a way more people can recover they account data before shutdown.

[Scripts.zip](https://github.com/kavezo/ZipZap/files/5431676/Scripts.zip)

**Comment by kavezo** [comment]
> Error point to _api\userPiece.py_. Line 204. Then go to Line 110 (Limit Break, idk why) and says _userPiece['piece']['pieceKind']=='LIMIT_BREAK'_ '**pieceKind': Wrong Key**

Ooh, good catch, I didn't see this during testing. I'll try to reproduce it and patch it up.

**Comment by gvaldebenit** [comment]
Ok, I got the file here. If you need anything more, don't hesistate on ask. At least I'm gonna make another backup on 30, so files would be here until then. 

[userPieceList.zip](https://github.com/kavezo/ZipZap/files/5433711/userPieceList.zip)

**Comment by kavezo** [comment]
Okay it turned out to be number 2 -- turns out only special memes like event memoria or cores have that property. Changed it to check for if the property exists first.

Thanks for finding this btw!
